#!/bin/bash
# Set up Kurtosis Ethereum testnet for Vixy integration tests
#
# This script:
#   1. Starts a Kurtosis enclave with Ethereum nodes
#   2. Extracts node endpoints
#   3. Generates Vixy configuration
#
# Usage:
#   ./scripts/setup-kurtosis.sh
#
# Prerequisites:
#   - Kurtosis CLI installed: https://docs.kurtosis.com/install/
#   - Docker installed and running

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
KURTOSIS_DIR="$PROJECT_DIR/kurtosis"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

echo_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

echo_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

echo_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

ENCLAVE_NAME="vixy-testnet"

# Check prerequisites
echo_info "Checking prerequisites..."

if ! command -v kurtosis &> /dev/null; then
    echo_error "Kurtosis CLI is not installed."
    echo_info "Install it from: https://docs.kurtosis.com/install/"
    echo_info "  brew install kurtosis-tech/tap/kurtosis-cli  # macOS"
    echo_info "  Or download from: https://github.com/kurtosis-tech/kurtosis-cli-release-artifacts"
    exit 1
fi

if ! docker info &> /dev/null; then
    echo_error "Docker daemon is not running. Please start Docker."
    exit 1
fi

# Check if enclave already exists
if kurtosis enclave inspect "$ENCLAVE_NAME" &> /dev/null; then
    echo_warn "Enclave '$ENCLAVE_NAME' already exists."
    read -p "Do you want to destroy and recreate it? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo_info "Destroying existing enclave..."
        kurtosis enclave rm -f "$ENCLAVE_NAME"
    else
        echo_info "Using existing enclave. Run 'kurtosis enclave rm $ENCLAVE_NAME' to start fresh."
    fi
fi

# Start Kurtosis enclave
echo_step "Starting Kurtosis Ethereum testnet..."
echo_info "This may take several minutes on first run (downloading images)..."

kurtosis run github.com/ethpandaops/ethereum-package \
    --enclave "$ENCLAVE_NAME" \
    --args-file "$KURTOSIS_DIR/network_params.yaml"

echo_info "Enclave started successfully!"

# Get enclave info
echo_step "Extracting node endpoints..."

# Get service info
SERVICES=$(kurtosis enclave inspect "$ENCLAVE_NAME" --full-uuids 2>/dev/null | grep -E "el-|cl-" || true)

if [[ -z "$SERVICES" ]]; then
    echo_warn "Could not find EL/CL services. Listing all services:"
    kurtosis enclave inspect "$ENCLAVE_NAME"
    echo_info "Please extract endpoints manually and update kurtosis/vixy-kurtosis.toml"
    exit 0
fi

# Generate Vixy config
echo_step "Generating Vixy configuration..."

CONFIG_FILE="$KURTOSIS_DIR/vixy-kurtosis.toml"

cat > "$CONFIG_FILE" << 'HEADER'
# Auto-generated Vixy configuration for Kurtosis testnet
# Generated by setup-kurtosis.sh

[global]
max_el_lag_blocks = 5
max_cl_lag_slots = 3
health_check_interval_ms = 5000
proxy_timeout_ms = 30000
max_retries = 3

[server]
host = "127.0.0.1"
port = 8080

[metrics]
enabled = true
host = "127.0.0.1"
port = 9090

HEADER

# Parse EL nodes
echo "" >> "$CONFIG_FILE"
echo "# EL Nodes" >> "$CONFIG_FILE"

EL_COUNT=0
while IFS= read -r line; do
    if [[ "$line" =~ el-.*-([0-9]+) ]]; then
        SERVICE_NAME=$(echo "$line" | awk '{print $1}')
        # Get the port mappings
        PORTS=$(kurtosis service inspect "$ENCLAVE_NAME" "$SERVICE_NAME" 2>/dev/null | grep -E "http|ws" || true)

        HTTP_PORT=$(echo "$PORTS" | grep -E "rpc.*http" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+" | head -1 || true)
        WS_PORT=$(echo "$PORTS" | grep -E "ws" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+" | head -1 || true)

        if [[ -n "$HTTP_PORT" ]]; then
            EL_COUNT=$((EL_COUNT + 1))
            IS_PRIMARY="false"
            [[ $EL_COUNT -eq 1 ]] && IS_PRIMARY="true"

            cat >> "$CONFIG_FILE" << EOF
[[el_nodes]]
name = "$SERVICE_NAME"
http_url = "http://$HTTP_PORT"
ws_url = "ws://${WS_PORT:-$HTTP_PORT}"
is_primary = $IS_PRIMARY

EOF
        fi
    fi
done <<< "$SERVICES"

# Parse CL nodes
echo "# CL Nodes" >> "$CONFIG_FILE"

CL_COUNT=0
while IFS= read -r line; do
    if [[ "$line" =~ cl-.*-([0-9]+) ]]; then
        SERVICE_NAME=$(echo "$line" | awk '{print $1}')
        # Get the port mappings
        PORTS=$(kurtosis service inspect "$ENCLAVE_NAME" "$SERVICE_NAME" 2>/dev/null | grep -E "http" || true)

        HTTP_PORT=$(echo "$PORTS" | grep -E "http" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+" | head -1 || true)

        if [[ -n "$HTTP_PORT" ]]; then
            CL_COUNT=$((CL_COUNT + 1))

            cat >> "$CONFIG_FILE" << EOF
[[cl_nodes]]
name = "$SERVICE_NAME"
url = "http://$HTTP_PORT"

EOF
        fi
    fi
done <<< "$SERVICES"

echo_info "Generated config: $CONFIG_FILE"
echo_info "Found $EL_COUNT EL nodes and $CL_COUNT CL nodes"

# Show next steps
echo ""
echo_step "Next steps:"
echo "  1. Review the generated config: cat $CONFIG_FILE"
echo "  2. If ports are missing, run: kurtosis enclave inspect $ENCLAVE_NAME"
echo "  3. Start Vixy: cargo run -- --config $CONFIG_FILE"
echo "  4. Run tests: cargo test --test integration_cucumber"
echo ""
echo_info "To stop the testnet: kurtosis enclave rm $ENCLAVE_NAME"
