#!/bin/bash
# Set up Kurtosis Ethereum testnet for Vixy integration tests
#
# This script:
#   1. Starts a Kurtosis enclave with Ethereum nodes
#   2. Extracts node endpoints
#   3. Generates Vixy configuration
#
# Usage:
#   ./scripts/setup-kurtosis.sh [--destroy]
#
# Prerequisites:
#   - Kurtosis CLI installed: https://docs.kurtosis.com/install/
#   - Docker installed and running

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
KURTOSIS_DIR="$PROJECT_DIR/kurtosis"

ENCLAVE_NAME="vixy-testnet"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

echo_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

echo_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

echo_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

# Handle --destroy flag
if [[ "$1" == "--destroy" ]]; then
    echo_info "Destroying Kurtosis enclave '$ENCLAVE_NAME'..."
    kurtosis enclave rm -f "$ENCLAVE_NAME" 2>/dev/null || echo_warn "Enclave not found"
    echo_info "Done."
    exit 0
fi

# Check prerequisites
echo_info "Checking prerequisites..."

if ! command -v kurtosis &> /dev/null; then
    echo_error "Kurtosis CLI is not installed."
    echo_info "Install it from: https://docs.kurtosis.com/install/"
    echo_info "  brew install kurtosis-tech/tap/kurtosis-cli  # macOS"
    echo_info "  Or download from: https://github.com/kurtosis-tech/kurtosis-cli-release-artifacts"
    exit 1
fi

if ! command -v jq &> /dev/null; then
    echo_error "jq is not installed."
    echo_info "Install it with: brew install jq  # macOS"
    exit 1
fi

if ! docker info &> /dev/null; then
    echo_error "Docker daemon is not running. Please start Docker."
    exit 1
fi

# Check if enclave already exists
if kurtosis enclave inspect "$ENCLAVE_NAME" &> /dev/null; then
    echo_info "Enclave '$ENCLAVE_NAME' already exists."
    echo_info "Extracting endpoints from existing enclave..."
else
    # Start Kurtosis enclave
    echo_step "Starting Kurtosis Ethereum testnet..."
    echo_info "This may take several minutes on first run (downloading images)..."

    kurtosis run github.com/ethpandaops/ethereum-package \
        --enclave "$ENCLAVE_NAME" \
        --args-file "$KURTOSIS_DIR/network_params.yaml"

    echo_info "Enclave started successfully!"
fi

# Get enclave info as JSON
echo_step "Extracting node endpoints..."

# Get all services
SERVICES_JSON=$(kurtosis enclave inspect "$ENCLAVE_NAME" --full-uuids 2>/dev/null || true)

# Generate Vixy config
echo_step "Generating Vixy configuration..."

CONFIG_FILE="$KURTOSIS_DIR/vixy-kurtosis.toml"

cat > "$CONFIG_FILE" << 'HEADER'
# Auto-generated Vixy configuration for Kurtosis testnet
# Generated by setup-kurtosis.sh
# Re-run the script to regenerate after enclave changes

[global]
max_el_lag_blocks = 5
max_cl_lag_slots = 3
health_check_interval_ms = 5000
proxy_timeout_ms = 30000
max_retries = 3

[server]
host = "127.0.0.1"
port = 8080

[metrics]
enabled = true
host = "127.0.0.1"
port = 9090

HEADER

# Extract EL nodes using kurtosis port print
echo "" >> "$CONFIG_FILE"
echo "# EL Nodes" >> "$CONFIG_FILE"

EL_COUNT=0
for i in 1 2 3; do
    # Try different EL service naming patterns
    for pattern in "el-$i-geth-lighthouse" "el-$i-geth-prysm" "el-$i-nethermind-teku" "el-$i-geth" "el-$i"; do
        HTTP_PORT=$(kurtosis port print "$ENCLAVE_NAME" "$pattern" rpc 2>/dev/null || true)
        WS_PORT=$(kurtosis port print "$ENCLAVE_NAME" "$pattern" ws 2>/dev/null || true)

        if [[ -n "$HTTP_PORT" ]]; then
            EL_COUNT=$((EL_COUNT + 1))
            IS_PRIMARY="false"
            [[ $EL_COUNT -eq 1 ]] && IS_PRIMARY="true"

            # Default WS to HTTP if not available
            [[ -z "$WS_PORT" ]] && WS_PORT="$HTTP_PORT"

            cat >> "$CONFIG_FILE" << EOF
[[el_nodes]]
name = "$pattern"
http_url = "http://$HTTP_PORT"
ws_url = "ws://$WS_PORT"
is_primary = $IS_PRIMARY

EOF
            echo_info "  Found EL node: $pattern at $HTTP_PORT"
            break
        fi
    done
done

# Extract CL nodes
echo "# CL Nodes" >> "$CONFIG_FILE"

CL_COUNT=0
for i in 1 2 3; do
    # Try different CL service naming patterns
    for pattern in "cl-$i-lighthouse-geth" "cl-$i-prysm-geth" "cl-$i-teku-nethermind" "cl-$i-lighthouse" "cl-$i"; do
        HTTP_PORT=$(kurtosis port print "$ENCLAVE_NAME" "$pattern" http 2>/dev/null || true)

        if [[ -n "$HTTP_PORT" ]]; then
            CL_COUNT=$((CL_COUNT + 1))

            cat >> "$CONFIG_FILE" << EOF
[[cl_nodes]]
name = "$pattern"
url = "http://$HTTP_PORT"

EOF
            echo_info "  Found CL node: $pattern at $HTTP_PORT"
            break
        fi
    done
done

# If no nodes found, show manual instructions
if [[ $EL_COUNT -eq 0 ]] && [[ $CL_COUNT -eq 0 ]]; then
    echo_warn "Could not auto-detect node endpoints."
    echo_info "Listing all services in enclave:"
    kurtosis enclave inspect "$ENCLAVE_NAME"
    echo ""
    echo_info "To find ports manually:"
    echo_info "  kurtosis port print $ENCLAVE_NAME <service-name> <port-name>"
    echo_info ""
    echo_info "Then edit: $CONFIG_FILE"
    exit 1
fi

echo_info "Generated config: $CONFIG_FILE"
echo_info "Found $EL_COUNT EL nodes and $CL_COUNT CL nodes"

# Show next steps
echo ""
echo_step "Kurtosis enclave is ready!"
echo ""
echo "  Start Vixy:  cargo run -- --config $CONFIG_FILE"
echo "  Run tests:   cargo test --test integration_cucumber"
echo "  Stop:        kurtosis enclave rm $ENCLAVE_NAME"
echo ""
